# Python Basics: Exploring Datasets with Pandas

This notebook introduces pandas, the most popular Python library for cleaning, organizing, and analyzing data. This session will focus on how pandas structures data and how to explore a dataset.

By the end of this notebook, you will be able to:
- Understand the two main data types that pandas uses, the Series and the DataFrame
- Get summary information on a DataFrame with attributes like `.columns` and `.shape`, and methods like `.head()` and `.value_counts()`
- Subset a DataFrame based on certain conditions
- Save a DataFrame to a CSV and read a CSV into a DataFrame

## Importing the Pandas Library

Before we can get started with pandas, we first need to import the library into our Python workspace. We do so with the following line of code:

In [1]:
import pandas as pd

When you first install Python from most sources, your computer will also install a number of common **libraries**, which are additional modules that extend the capabilities of base Python. 

The code `import pandas as pd` instructs Python to do two things:
- Load the pandas library into our current workspace
- Assign pandas to `pd`. Now, whenever we reference `pd`, Python will know that we are accessing some capability of pandas.

## The Pandas Series and DataFrame
In Pandas, data are stored in two fundamental objects: 

* **Pandas Series** - a single column or row of data
* **Pandas DataFrame** - a table of data containing multiple columns and rows

### Pandas Series

We can think of a Series as a single column or row of data. Here we have a column called `Champions` with the country names of the winners of the most recent ten FIFA world cup games.

|Champions|
|---|
|Argentina|
|France|
|Germany|
|Spain|
|Italy|
|Brazil|
|France|
|Brazil|
|Germany|
|Argentina|

Let's create a Series based on this column. To create our Series, we pass a **list** into the `.Series()` method:

In [2]:
# Create a data series object in Pandas
champions = pd.Series(["Argentina",
                       "France", 
                       "Germany", 
                       "Spain", 
                       "Italy", 
                       "Brazil", 
                       "France", 
                       "Brazil", 
                       "Germany",
                       "Argentina"]
                    )

In [ ]:
champions

In some ways, Series objects behave similar to lists in Python. For example, you can access a particular value in a Series using its index inside square brackets, or you can iterate over it using a `for` loop:

In [ ]:
# Access an item in the series using its index:
champions[4]

In [ ]:
for winner in champions:
    print(winner)

### Pandas DataFrame

While a Pandas Series is 1-dimensional with a single column/row of data, a Pandas DataFrame is 2-dimensional and can have multiple columns and rows. 

|Year|Champion|Host|
|---|---|---|
|2022|Argentina|Qatar|
|2018|France|Russia|
|2014|Germany|Brazil|
|2010|Spain|South Africa|
|2006|Italy|Germany|
|2002|Brazil|Korea/Japan|
|1998|France|France|
|1994|Brazil|USA|
|1990|Germany|Italy|
|1986|Argentina|Mexico|

Let's create a Pandas DataFrame based on this table. To create our dataframe, we pass lists of three items each into the `DataFrame()` method. Each of these lists is one row of the DataFrame. We also set a list of `columns` to specify the name for each column.

In [3]:
# Create a Pandas dataframe
wcup = pd.DataFrame(
    data=[
        [2022, "Argentina", "Qatar"],
        [2018, "France", "Russia"],
        [2014, "Germany", "Brazil"],
        [2010, "Spain", "South Africa"],
        [2006, "Italy", "Germany"],
        [2002, "Brazil", "Korea/Japan"],
        [1998, "France", "France"],
        [1994, "Brazil", "USA"],
        [1990, "Germany", "Italy"],
        [1986, "Argentina", "Mexico"]
    ],
    columns=["Year", "Winner", "Host"]
)

wcup

   Year     Winner          Host
0  2022  Argentina         Qatar
1  2018     France        Russia
2  2014    Germany        Brazil
3  2010      Spain  South Africa
4  2006      Italy       Germany
5  2002     Brazil   Korea/Japan
6  1998     France        France
7  1994     Brazil           USA
8  1990    Germany         Italy
9  1986  Argentina        Mexico

### The Index

Note that in addition to the three columns we created, the DataFrame displayed a series of integers 0-9 on the lefthand side. This is the DataFrame's **index**. By default, the index is a series of integers starting with 0, but it is possible to set other values for our index (for example, we could use the Year column as our index). 

We will revisit the index when we look at accessing specific rows or columns of our data.

### The Relationship Between DataFrames and Series

In a Pandas dataframe, each row/column is technically a Pandas Series. We can see this by selecting one column and checking its type.

In [ ]:
type(wcup["Year"])

## Explore the data

After we build a dataframe, it is helpful to get a general idea of the data. The first step is to explore the dataframe's attributes. Attributes are properties of the dataframe (not functions), so they do not have parentheses `()` after them. 

|Attribute|Reveals|
|---|---|
|`.shape`| The number of rows and columns|
|`.columns`| The name of each column|


To see how many rows and columns a dataframe has, we use the `.shape` attribute. `df.shape` returns an object known as a tuple with (number of rows, number of columns).

In [ ]:
wcup.shape

In [ ]:
# Try accessing the columns of wcup:

There are some methods we can use to explore the data as well. 


|Method|Reveals|
|---|---|
|`.head(n)`| First `n` rows|
|`.tail(n)`| Last `n` rows|
|`.sample(n)`| `n` randomly selected rows|

In [ ]:
# Try using one of the methods above on wcup:

## Selecting Specific Columns

We can select just one column of data in the format `df["column_name"]`, which will return the data as a Series.

In [4]:
wcup["Winner"]

0    Argentina
1       France
2      Germany
3        Spain
4        Italy
5       Brazil
6       France
7       Brazil
8      Germany
9    Argentina
Name: Winner, dtype: object

If we want to look at multiple columns, we instead pass those columns as a list to the DataFrame. Selecting multiple columns from a DataFrame will return a new (smaller) DataFrame.

In [5]:
columns_to_select = ["Winner", "Host"]

wcup[columns_to_select]

      Winner          Host
0  Argentina         Qatar
1     France        Russia
2    Germany        Brazil
3      Spain  South Africa
4      Italy       Germany
5     Brazil   Korea/Japan
6     France        France
7     Brazil           USA
8    Germany         Italy
9  Argentina        Mexico

## Selecting a Specific "Cell"

If you've worked in Excel previously, you are likely familiar with referring to data points as "cells," where each cell can be referred to by a combination of its column (a letter) and its row (a number). For example, for a simple table in Excel, data might be laid out like this: 
||A|B|C|
|---|---|---|---|
|1|A1|B1|C1|
|2|A2|B2|C2|
|3|A3|B3|C3|

While pandas users don't typically refer to individual cells, it can be a helpful way of thinking about how data in a DataFrame is laid out. We can reference and select a specific cell by referring to it using its column name and index name with the following syntax:

`dataframe_name[column][index]`

In our `wcup` DataFrame, our column names are strings (text), and our index is composed of integers (numbers). Remember that in Python, indexes start at 0, so to select the first value in the "Winner" column, we would use the following code:

In [6]:
# Select the value in the "Winner" column at index 0:
wcup["Winner"][0]

'Argentina'

Try writing your own code to select the fourth value in the "Host" column:

In [ ]:
# Select the fourth value in the "Host" column:

## `.value_counts()` and `.unique()`

We've looked at some ways to explore a DataFrame as a whole, but we can dig even more into individual columns. Once we have subset our DataFrame to a single column, we can use `.value_counts()` to get a table of the number of times that each value occurs in the column. We can also get a list of unique values (without their counts) using `.unique()`.

In [ ]:
wcup["Winner"].value_counts()

In [ ]:
wcup["Host"].unique()

## Sorting a DataFrame

To reorder the rows in a DataFrame, we can use `.sort_values(by=column)`, specifying the name of the column we would like to use to sort the data.

In order to sort by a column, all the data in that column must be of the same (or comparable) type. For example, strings can all be sorted alphabetically, or numbers (floats and integers) can be sorted numerically.

In [ ]:
# Sort the DataFrame by year:
wcup.sort_values(by="Year")

`.sort_values()` has an optional additional parameter, `ascending`. By default, pandas sorts a DataFrame in ascending order (e.g. from A to Z or from lowest number to highest number). To reverse the order, we can include `ascending=False` in the function call.

In [ ]:
# Sort the DataFrame in reverse alphabetical order by winner:
wcup.sort_values(by="Winner", ascending=False)

In the cell below, try sorting the data by the name of the host country.

In [ ]:
# Sort the DataFrame by host country:

## Subsetting a DataFrame Based on a Condition

Oftentimes, we will want to work with only a subset of our DataFrame that meets some condition. For example, we may want to only work with rows in our `wcup` DataFrame where Germany was the winner, or only games played after 2000.

We do this in two steps. First, we write a **comparison operator** expression to check which rows in a column meet a given condition.

For example, the line below checks for rows where the value of "Winner" is equal to "Germany" and returns a Series containing the boolean values True (for rows where the condition is met) and False (for rows where the condition is not met).

In [ ]:
wcup["Winner"] == "Germany"

This Series of True/False values is sometimes called a **mask**. When we pass it into our original DataFrame, it will return only the rows where the condition is met.

In [ ]:
# Step 1: Create a mask for the condition we want to use to subset our data:
mask = wcup["Winner"] == "Germany"

# Step 2: Pass the mask to the original DataFrame:
wcup[mask]

Try writing code to subset the DataFrame to only World Cup matches after the year 2000.

(Hint: The "Year" column contains integer values. Instead of using the `==` comparison operator, use `>` or `<`.)

In [ ]:
# Step 1: Create a mask for the condition we want to use to subset our data:

# Step 2: Pass the mask to the original DataFrame:

## Writing a DataFrame to a File

Now that we've created our `wcup` DataFrame, let's save it to a file so that we can use it in other programs. One of the most common formats for saving tabular data is as a CSV file, because it is a simple format that can be used in a wide variety of software environments, including Excel.

To save a DataFrame to a file, we will use the method `.to_csv()`. 

Specifically, we will write `wcup.to_csv("wcup_winners.csv", index=False)`. The name for our file should always end in `.csv`.

In [ ]:
wcup.to_csv("wcup_winners.csv", index=False)

Why do we specify `index=False`? In this case, our index is just a default list of integers and isn't useful for working with the data, so we can drop it. 

But to see the difference, try saving the DataFrame again without `index=False`.

In [ ]:
# Rerun the code saving wcup again, but remove index=False:

<h3 style="color:red; display:inline">Warning!</h3>

Notice that Python let us save a new version of our data without warning that we were deleting anything. **Python does not warn you when you are about to overwrite a file!** For this reason, it's very important to make sure you only overwrite a file if you have an easy way to recover the previous version. In this case, we can restore the original version of the file by rerunning `wcup.to_csv("wcup_winners.csv", index=False)`, so we're all good!

## Reading a DataFrame from a File

We created the `wcup` DataFrame from scratch using lists in Python, but in the vast majority of cases, you'll likely be working with tabular data created elsewhere that you will load into Python. To create a DataFrame from a CSV, we use `pd.read_csv()`, making sure to save the new DataFrame to a variable.

Let's load in the `wcup_winners.csv` file we just created.

In [ ]:
# Load in the wcup_winners.csv file
wcup2 = pd.read_csv("wcup_winners.csv")

## Try It Out: Exploring a New Dataset

So far, we've just been working with toy data. To work with some real data, we will use the National Weather Service's API to get the forecast for Lexington for the upcoming week and assigning it to a variable `forecast`.

In [ ]:
# Import another library, requests, to access data from the Internet,
# then contact the National Weather Service for forecast data
# and save it to a DataFrame:
import requests
url = "https://api.weather.gov/gridpoints/LMK/94,71/forecast/hourly"
data = response_data = requests.get(url).json()
forecast = pd.DataFrame(data["properties"]["periods"])

Using the same techniques for exploring `wcup` above, try writing your own code to answer the following questions about the `forecast` dataset:
- How many rows and columns does it contain?
- What are the names of the columns?
- How many times does each forecast type appear in the `"shortForecast"` column?
- What values occur in the `"temperatureTrend"` column?
- For rows where `"isDayTime"` is True, how many times does each windspeed appear?

In [ ]:
# Explore the dataset here:
# You can write code for each answer in an individual cell,
# or you can wrap your code inside a print() statement
# so you can output all information in a single cell.

Finally, save the DataFrame to a CSV, and open it in another software, such as Excel. Does its content match what you observed through pandas?

In [ ]:
# Save the forecast data to a CSV:

# Continue Your Pandas Journey

There are many more methods for exploring datasets in pandas than we had time to cover here. For the most thorough overview of everything pandas has to offer, see the e-book [Python for Data Analysis (3rd Edition)](https://wesmckinney.com/book/) by Wes McKinney, the creator of pandas.

For tutorial-based learning, download the following notebooks from Constellate and run them in Jupyter:
- **Pandas Basics 1:** https://github.com/ithaka/constellate-notebooks/blob/master/Pandas-basics/pandas-basics-1.ipynb
- **Pandas Basics 2:** https://github.com/ithaka/constellate-notebooks/blob/master/Pandas-basics/pandas-basics-2.ipynb
- **Pandas Basics 3:** https://github.com/ithaka/constellate-notebooks/blob/master/Pandas-basics/pandas-basics-3.ipynb
- **Pandas Intermediate 1:** https://github.com/ithaka/constellate-notebooks/blob/master/Python-intermediate/python-intermediate-1.ipynb
- **Pandas Intermediate 2:** https://github.com/ithaka/constellate-notebooks/blob/master/Python-intermediate/python-intermediate-2.ipynb
- **Pandas Intermediate 3:** https://github.com/ithaka/constellate-notebooks/blob/master/Python-intermediate/python-intermediate-3.ipynb
- **Pandas Intermediate 4:** https://github.com/ithaka/constellate-notebooks/blob/master/Python-intermediate/python-intermediate-4.ipynb
- **Pandas Intermediate 5:** https://github.com/ithaka/constellate-notebooks/blob/master/Python-intermediate/python-intermediate-5.ipynb

# Acknowledgments
<img align="left" src="https://ithaka-labs.s3.amazonaws.com/static-files/images/tdm/tdmdocs/CC_BY.png"><br />

This lesson was created by Isaac Wink, with sections of the code and text adapted from [Pandas Basics 1](https://github.com/ithaka/constellate-notebooks/blob/master/Pandas-basics/pandas-basics-1.ipynb) by Zhuo Chen for [JSTOR Labs](https://labs.jstor.org/) amd generously shared under a [Creative Commons CC BY License](https://creativecommons.org/licenses/by/4.0/).<br />